// ---------------------------------------------------------------
// Copyright (c) Paul.Ward@ccoder.co.uk
// ---------------------------------------------------------------

using cCoder.CodeAnalysis.Models;
using cCoder.CodeAnalysis.Services.Foundations.Architectures;
using cCoder.CodeAnalysis.Services.Processings.Architectures;
using FluentAssertions;
using Microsoft.CodeAnalysis.CSharp;
using Moq;

namespace cCoder.CodeAnalysis.Tests.Services.Processings.Architectures;

public sealed class ArchitectureProcessingServiceTests
{
    [Fact]
    public void ProcessShouldExcludeGeneratedSyntaxTrees()
    {
        CSharpCompilation compilation = CSharpCompilation.Create(
            assemblyName: "Example",
            syntaxTrees:
            [
                CSharpSyntaxTree.ParseText(
                    text: "public sealed class Student { }",
                    path: "Student.cs"),
                CSharpSyntaxTree.ParseText(
                    text:
                        """
                        // <auto-generated/>
                        public sealed class GeneratedPage
                        {
                            public void Render()
                            {
                                if (true)
                                {
                                }
                            }
                        }
                        """,
                    path: "obj/GeneratedPage.g.cs"),
                CSharpSyntaxTree.ParseText(
                    text:
                        """
                        //------------------------------------------------------------------------------
                        // <auto-generated>
                        //     This code was generated by a tool.
                        // </auto-generated>
                        public sealed class GeneratedOpenApiSupport { }
                        """,
                    path: "OpenApiXmlCommentSupport.generated.cs"),
            ]);
        ArchitectureBuild build = new()
        {
            Compilation = compilation,
        };
        Mock<IArchitectureService> architectureServiceMock = new();
        architectureServiceMock
            .Setup(service => service.Build(compilation))
            .Returns(build);
        ArchitectureProcessingService service =
            new(architectureServiceMock.Object);

        ArchitectureBuild result = service.Process(compilation);

        result.Architecture.Classes
            .Select(item => item.Name)
            .Should()
            .ContainSingle()
            .Which.Should()
            .Be("Student");
    }
}
