<Project>
  <PropertyGroup>
    <cCoderCodeAnalysisBuildTaskDirectory Condition="'$(cCoderCodeAnalysisBuildTaskSourceDirectory)' != ''"
      >$([System.IO.Path]::GetTempPath())cCoder.CodeAnalysis.BuildTasks\$([System.Guid]::NewGuid())\</cCoderCodeAnalysisBuildTaskDirectory>
    <cCoderCodeAnalysisBuildTaskAssembly Condition="'$(cCoderCodeAnalysisBuildTaskSourceDirectory)' != ''"
      >$(cCoderCodeAnalysisBuildTaskDirectory)cCoder.CodeAnalysis.BuildTasks.dll</cCoderCodeAnalysisBuildTaskAssembly>
    <cCoderCodeAnalysisBuildTaskAssembly Condition="'$(cCoderCodeAnalysisBuildTaskAssembly)' == ''"
      >$(MSBuildThisFileDirectory)..\tools\net10.0\cCoder.CodeAnalysis.BuildTasks.dll</cCoderCodeAnalysisBuildTaskAssembly>
  </PropertyGroup>
  <UsingTask
    TaskName="cCoder.CodeAnalysis.BuildTasks.GenerateArchitectureTask"
    AssemblyFile="$(cCoderCodeAnalysisBuildTaskAssembly)"
  />
  <PropertyGroup>
    <cCoderCodeAnalysisGenerateArchitecture Condition="'$(cCoderCodeAnalysisGenerateArchitecture)' == ''"
      >true</cCoderCodeAnalysisGenerateArchitecture>
    <cCoderCodeAnalysisArchitecturePath Condition="'$(cCoderCodeAnalysisArchitecturePath)' == ''"
      >$(MSBuildProjectDirectory)\project.stxjson</cCoderCodeAnalysisArchitecturePath>
  </PropertyGroup>
  <Target Name="cCoderPrepareArchitectureBuildTask" Condition="'$(cCoderCodeAnalysisBuildTaskSourceDirectory)' != ''">
    <ItemGroup>
      <cCoderCodeAnalysisBuildTaskFile Include="$(cCoderCodeAnalysisBuildTaskSourceDirectory)*" />
    </ItemGroup>
    <MakeDir Directories="$(cCoderCodeAnalysisBuildTaskDirectory)" />
    <Copy
      SourceFiles="@(cCoderCodeAnalysisBuildTaskFile)"
      DestinationFolder="$(cCoderCodeAnalysisBuildTaskDirectory)"
      SkipUnchangedFiles="true"
    />
  </Target>
  <Target
    Name="cCoderGenerateArchitecture"
    AfterTargets="Build"
    DependsOnTargets="cCoderPrepareArchitectureBuildTask"
    Condition="'$(cCoderCodeAnalysisGenerateArchitecture)' == 'true'
      and '$(IsTestProject)' != 'true'
      and '$(DesignTimeBuild)' != 'true'"
  >
    <GenerateArchitectureTask
      ProjectPath="$(MSBuildProjectFullPath)"
      OutputPath="$(cCoderCodeAnalysisArchitecturePath)"
    />
  </Target>
</Project>
